// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFOA3AFmYlqNCA5DtsL1TiV3r2qrMNgY',
    appId: '1:828986216096:web:7dc35b5d1754628f8283c5',
    messagingSenderId: '828986216096',
    projectId: 'mickiefitness',
    authDomain: 'mickiefitness.firebaseapp.com',
    storageBucket: 'mickiefitness.appspot.com',
    measurementId: 'G-HLH1G44BEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6KQ14DzKJPXw3bjuKgo462LiwT3uWFM',
    appId: '1:828986216096:android:719c59158f29facb8283c5',
    messagingSenderId: '828986216096',
    projectId: 'mickiefitness',
    storageBucket: 'mickiefitness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknQOnnJAJiYJnjLORuf_KGVsNNNzvBF8',
    appId: '1:828986216096:ios:a3f2f0a818879a318283c5',
    messagingSenderId: '828986216096',
    projectId: 'mickiefitness',
    storageBucket: 'mickiefitness.appspot.com',
    iosClientId:
        '828986216096-hf2hag3b0un0c4ur3bigrhf0nlf911lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.morrfFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknQOnnJAJiYJnjLORuf_KGVsNNNzvBF8',
    appId: '1:828986216096:ios:a3f2f0a818879a318283c5',
    messagingSenderId: '828986216096',
    projectId: 'mickiefitness',
    storageBucket: 'mickiefitness.appspot.com',
    iosClientId:
        '828986216096-hf2hag3b0un0c4ur3bigrhf0nlf911lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.morrfFlutter',
  );
}
